version: "3.8"

services:
  frontend:
    build: ./front_end #where we have the Dockerfile (frontend)
    ports:
      - 3000:3000 #port3000 of the host - port 3000 of the container
    volumes:
      - ./front_end:/app
  backend:
    build: ./back_end #where we have the Dockerfile (backend)
    depends_on:
      - db
    ports:
      - 3001:3001 #port3001 of the host - port 3001 of the container
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: db
      #DATABASE_URL: postgres://postgress:postgres@db:5432/db
    links:
      - db
    volumes:
      - ./back_end:/app
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes: 
      - db_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    user: root
    environment:
      PGADMIN_DEFAULT_EMAIL: isaialbarran@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8080:80"
      - "8443:443"
    volumes: 
      - db_data:/var/lib/pgadmin
volumes:
  # postgres database persistence
  db_data:
    driver: local
  # pgadmin config persistence
  pgadmin_data:
    driver: local
  